ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(30);

ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_phone;
ALTER TABLE users ADD CONSTRAINT uq_users_phone UNIQUE (phone);

ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
